<html>
<head>
    <meta name="layout" content="${gspLayout ?: 'main'}"/>
    <title><g:message code="springSecurity.createuser.title"></g:message></title>
</head>

<body>
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="card-title text-center"><g:message code="springSecurity.createuser.header"></g:message></h5>
                <g:render template="/templates/grailstemplates"/>
                <form class="form-signin" action="createUser" method="POST" id="createUserForm" autocomplete="off">
                    <div class="form-group">
                        <label for="role"><g:message code="springSecurity.register.role"></g:message></label>
                        <g:select class="form-control" name="roleid"
                                  from="${com.grailsapplication.Role.list()}"
                                  optionKey="id"/>
                    </div>

                    <div class="form-group">
                        <label for="firstname">*<g:message
                                code="springSecurity.register.firstname.label"></g:message></label>
                        <input type="text" placeholder="First Name" class="form-control" name="firstname"
                               id="firstname"
                               autocapitalize="none" required/>
                    </div>

                    <div class="form-group">
                        <label for="lastname"><g:message
                                code="springSecurity.register.lastname.label"></g:message></label>
                        <input type="text" placeholder="Last Name" class="form-control" name="lastname"
                               id="lastname"
                               autocapitalize="none"/>
                    </div>

                    <div class="form-group">
                        <label for="email">*<g:message code="springSecurity.register.email.label"></g:message></label>
                        <input type="text" placeholder="Email Address" class="form-control" name="email" id="email"
                               autocapitalize="none" required/>
                    </div>

                    <div class="form-group">
                        <label for="mobilenumber"><g:message
                                code="springSecurity.register.mobilenumber.label"></g:message></label>
                        <input type="text" placeholder="Mobile Number" class="form-control" name="mobilenumber"
                               id="mobilenumber"
                               autocapitalize="none"/>
                    </div>


                    <div class="form-group">
                        <label for="username">*<g:message
                                code="springSecurity.login.username.label"></g:message></label>
                        <input type="text" placeholder="Username" class="form-control" name="username"
                               id="username"
                               autocapitalize="none" required/>
                    </div>

                    <div class="form-group">
                        <label for="password">*<g:message
                                code="springSecurity.login.password.label"></g:message></label>

                        <p><g:message
                                code="springSecurity.autogenerated.password.label"></g:message>
                            <tr>
                                <td>
                                    <input type="radio" name="autopassword" onclick="showPassword()"
                                          id="radio1" value="true"/><span class="bold-txt"><g:message
                                        code="auto.generate.password.yes"/></span>
                                </td>
                                <td>
                                    <input type="radio" name="autopassword" onclick="typePassword()" value="false"
                                          id="radio2" checked="checked"/><span class="bold-txt"><g:message
                                        code="auto.generate.password.no"/></span>
                                </td>
                            </tr>
                            <link rel="stylesheet"
                                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

                        <div class="input-group mb-2 mr-sm-2">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i id="pass-status" class="fa fa-eye" aria-hidden="true"
                                       onClick="viewPassword()"></i>
                                </div>
                            </div>
                            <input type="password" class="form-control" name="password" value=""
                                   id="password" required/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password">*<g:message
                                code="springSecurity.confirm.password.label"></g:message></label>
                        <input type="password" placeholder="confirm password" class="form-control" name="repassword"
                               id="repassword"/>
                    </div>

                    <button id="submit" class="btn btn-lg btn-primary btn-block text-uppercase" type="submit"><g:message
                            code="default.add.user.button"></g:message></button>
                    <hr class="my-4">
                </form>
                <g:form controller="userManagement">
                    <button id="cancel" class="btn btn-lg btn-secondary btn-block text-uppercase"
                            type="submit"><g:message code="default.button.cancel"></g:message></button>
                </g:form>
            </div>
        </div>
    </div>
</div>
<asset:javascript src="validator.js"/>
<g:javascript>
    document.addEventListener("DOMContentLoaded", function (event) {
        document.forms['createUserForm'].elements['firstname'].focus();
    });
    function generatepassword() {
        var randomstring = Math.random().toString(36).slice(-8);
        return randomstring
    }
    function showPassword() {
        var pass = generatepassword()
        document.getElementById("password").setAttribute('value', pass);
        $('#reenterpassword').hide()
        $('#password').show()
    }
    function typePassword() {
        document.getElementById("password").setAttribute('value', '');
        $('#password').show()
        $('#reenterpassword').show()
    }
</g:javascript>
</body>
</html>